<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<title><?= $this->title; ?> | UberGallery - The Simple PHP Photo Gallery</title>
<link rel="stylesheet" type="text/css" href="/css/style.css" />
<? if(is_array($this->css)): ?>
    <? foreach($this->css as $css): ?>
        <link rel="stylesheet" type="text/css" href="<?= $css; ?>" />
    <? endforeach; ?>
<? endif; ?>
<!--[if IE]><style type="text/css">@import "/css/ie-fixes.css";</style><![endif]-->
<? if(is_array($this->js)): ?>
    <? foreach($this->js as $js): ?>
        <script type="text/javascript" src="<?= $js; ?>"></script>
    <? endforeach; ?>
<? endif; ?>
<link rel="shortcut icon" href="/images/images.png" />
<meta name="keywords" content="UberGallery, photo gallery, php, Chris Kankiewicz" />
</head>

<body>

<div id="wrapper">
    <div id="header" class="clearfix">
        <div id="title"><img src="/images/ubergallery_logo.png" alt="UberGallery" /></div>
    </div>
    <div id="navbar" class="clearfix">
        <ul id="navigation" class="left">
            <li><a href="/">Home</a></li>
            <li><a href="/demo">Demo</a></li>
            <li><a href="/news">News</a></li>
            <li><a href="/installation">Installation</a></li>
            <li><a href="/configuration">Configuration</a></li>
        </ul>
        <ul id="follow-us" class="right">
            <li class="title">Follow Us:</li>
            <li><a href="http://www.github.com/PHLAK/ubergallery" title="Github"><img src="/images/social-icons/github_16.png" alt="Github" /></a></li>
            <li><a href="http://www.twitter.com/ubergallery" title="Twitter"><img src="/images/social-icons/twitter_16.png" alt="Twitter" /></a></li>
            <li><a href="http://ubergallery.tumblr.com/rss" title="News Feed"><img src="/images/social-icons/rss_16.png" alt="News Feed" /></a></li>
        </ul>
    </div>
    <h1 id="page-title"><?= $this->title; ?></h1>
    <div id="content" class="clearfix">
        <? // <center><h2 id="announce">CK-Gallery is now UberGallery!</h2></center> ?>
        <?= $this->layout()->content; ?>
    </div>

    <div id="footer" class="clearfix">
        <span class="left">&copy; <?= date('Y'); ?> &bull; Chris Kankiewicz &bull; Some Rights Reserved</span>
        <span class="right"><a href="#">Sitemap</a> &bull; Design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a></span>
    </div>
</div>

<!-- Page design by, Chris Kankiewicz <http://www.chriskankiewicz.com> -->

<!-- GOOGLE ANALYTICS -->
<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {var pageTracker = _gat._getTracker("UA-967293-13");
    pageTracker._trackPageview(); } catch (err) {}
</script>
<!-- /GOOGLE ANALYTICS -->

</body>
</html>