<h3>Included Files/Folders</h3>

<pre>
ubergallery/
|  cache/                        - Default cache directory
|  images/                       - Default image directory (put your images here)
|  resources/
|  |  css/                       - Script styles
|  |  |  colorbox.css
|  |  |  ubergallery.css
|  |  images/                    - Script images
|  |  |  bg.png
|  |  |  border.png
|  |  |  controls.png
|  |  |  images.png
|  |  |  loading.gif
|  |  |  loading_background.png
|  |  |  page_white_stack.png
|  |  js/                        - Script JavaScript
|  |  |  jquery.colorbox.js
CHANGELOG.txt                    - UberGallery changelog
GPL-LICENSE.txt                  - GNU Public License v2.0
MIT-LICENSE.txt                  - MIT License
README                           - Basic README file
index.php                        - Main gallery script
</pre>

<div class="hr"><hr /></div>

<h2>Pagination</h2>

<p>To enable pagination, open index.php, find <tt>$imgPerPage = 0;</tt>
at the top and set this value to the number of images you would like to
display per page.</p>

<p><strong>NOTE:</strong> If pagination is enabled, the script will
generate thumbnails on a per-page basis. You do not have to worry about
this though, the first time a visitor visits a page without thumbnails,
it will automatically generate the thumbnails, however this may cause
the page to take several seconds to load the first time it processes.</p>

<div class="hr"><hr /></div>

<h2>Page Caching</h2>

<p>Page caching can drastically reduce the CPU load on your server
and is more efficient for servers with high traffic. To enable page
caching, edit the "$expireTime = 0;" value found at the top of the
ubergallery/ubergallery.php script. This value is the time in minutes
after which a new cach file will be generated.</p>

<p><strong>NOTE:</strong> At the moment, if you upload new images or
make a change to the script while caching is enabled, you will have to
delete the cache files or wait the ammouont of time specified before
your changes will be reflected on the page.</p>

<p>To delete the cache files, use an FTP program or shell access to
delete the "gallery-cache" folder and all of it's contents.</p>

<div class="hr"><hr /></div>

<h2>Update Notifications</h2>

<p>To enable the update notification, open index.php, find <tt>$verCheck
= false;</tt> and change this value to <tt>true</tt>. Once done, whenever an
update to UberGallery is available, a message will appear at the bottom
of your gallery informing you of this new version and providing a link
to the new version.</p>

<p>You may also get update notifications by following
<a href="http://twitter.com/ubergallery">@ubergallery</a> on Twitter.</p>

<div class="hr"><hr /></div>

<h2>Customizing your Gallery</h2>

<p>The UberGallery comes with class and id elements already in
place, this allows for customization of the look and feel of your
gallery. All you have to do is edit the CSS style sheet, or create your
own, and you'll be off in no time.</p>

<p>This is the typical structure of the XHTML output:</p>

<pre>
&lt;div id="gallery-wrapper"&gt;
  &lt;div id="gallery-constraint"&gt;
    &lt;div id="gallery-header"&gt;UberGallery Image Gallery&lt;/div&gt;
    &lt;div id="gallery-images"&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
    &lt;/div&gt;
    &lt;div id="uber-footer"&gt;
      &lt;div id="credit"&gt;Credit...&lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>

<p>Also, here's the pagination navigation structure:</p>

<pre>
&lt;ul id="uber-pagination"&gt;
  &lt;li class="inactive"&gt;&amp;lt;&lt;/li&gt;
  &lt;li class="current-page"&gt;1&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=2"&gt;2&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=3"&gt;3&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=4"&gt;4&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=2"&gt;&amp;gt;&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
</pre>