<h2>Customizing your Gallery</h2>

<p>The UberGallery comes with class and id elements already in
place, this allows for customization of the look and feel of your
gallery. All you have to do is edit the CSS style sheet, or create your
own, and you'll be off in no time.</p>

<p>This is the typical structure of the XHTML output:</p>

<pre>
&lt;div id="gallery-wrapper"&gt;
  &lt;div id="gallery-constraint"&gt;
    &lt;div id="gallery-header"&gt;UberGallery Image Gallery&lt;/div&gt;
    &lt;div id="gallery-images"&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
      &lt;a href="#"&gt;&lt;img src="#" /&gt;&lt;/a&gt;
    &lt;/div&gt;
    &lt;div id="uber-footer"&gt;
      &lt;div id="credit"&gt;Credit...&lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>

<p>Also, here's the pagination navigation structure:</p>

<pre>
&lt;ul id="uber-pagination"&gt;
  &lt;li class="inactive"&gt;&amp;lt;&lt;/li&gt;
  &lt;li class="current-page"&gt;1&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=2"&gt;2&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=3"&gt;3&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=4"&gt;4&lt;/a&gt;&lt;/li&gt;
  &lt;li&gt;&lt;a href="?page=2"&gt;&amp;gt;&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
</pre>