<h2>The Simple PHP Photo Gallery</h2>
<p>UberGallery is a simple, yet powerful, PHP photo gallery that
will basically manage itself for you. UberGallery supports .jpg, .gif
and .png image types, and will automatically creates thumbnails on the
fly. The main feature of this gallery is it automatically outputs XHTML
compliant markup for inclusion on a web page. The UberGallery will also
automatically prune it's thumbnails, so when you delete an image from
the images folder, it will delete the corresponding thumbnail. The
gallery also creates a log file for reference and debugging. The
UberGallery is licensed under the MIT License.</p>

<p>UberGallery also includes dynamic pagination. This allows users
with larger galleries to split the gallery up into several smaller pages
so visitors can easily browse those pages using a navigation bar below
the gallery. GZip compression is also implemented on the default
index.php file included with the gallery which helps to reduce bandwidth
usage and improves page load times significantly.</p>

<p>Starting with v1.6.3 UberGallery is dual licensed under the <a href="http://creativecommons.org/licenses/MIT/">MIT license</a> and <a href="http://creativecommons.org/licenses/GPL/2.0/">GPL 2.0 license</a>.</p>

<div class="hr"><hr /></div>

<h2>Download</h2>


<a href="http://github.com/PHLAK/ubergallery/downloads" title="Download UberGallery" id="dl-box">
    <strong>Download UberGallery</strong>
    <span class="version">v1.6.3</span><br />
    <span class="updated">Last Updated: May 14, 2010</span>
</a>

<div class="hr"><hr /></div>

<h3>Requirements</h3>

<p>Due to technical limitations of the functions used, you must be
running PHP version 4.0.6 or higher in a Linux environment, or version
4.3.0 on a Windows environment. Also, you must have PHP GD version
2.0.1 or later installed (2.0.28 or later is recommended).</p>

<p>The oldest PHP version this script has been successfully tested
on was a Linux system running PHP version 4.3.11 and PHP GD version
2.0.28, if you've tested UberGallery successfully on an older version of
Linux or on any Windows server, I'd like to know, please contact me.</p>

<p>For more information on PHP and PHP GD, please see <a href="http://www.php.net">http://www.php.net</a></p>

<div class="hr"><hr /></div>

<h2>Contact</h2>

<p>If you have any questions or comments, please email me at:
<a href="mailto:Chris@ChrisKankiewicz.com">Chris@ChrisKankiewicz.com</a></p>

<p>To report a bug, visit the issue tracker on Github at: <a href="http://github.com/PHLAK/ubergallery/issues">http://github.com/PHLAK/ubergallery/issues</a></p>

<div class="hr"><hr /></div>

<h2>Shout Outs</h2>
<p>Thanks go out to <a href="http://dualisanoob.com">Dual</a> for
inadvertently inspiring me to get up off my ass and program this.</p>

<p>Also, thanks to <a href="http://www.blastwavelabs.com">
Penguin</a> for answering questions throughout the entire development
process and for some bug testing.</p>

<p>Thanks also to <a href="http://www.wetwarehacks.com">Nak</a> for
rigorous beta testing that helped me iron out a number of bugs and fix
backwards capabilities.</p>

<p>Obligatory thanks to Hexatex for pen testing the crap out of this
script and helping me find and patch many vulnerabilities.</p>

<p>Lastly, thanks to the <a href="http://www.stackoverflow.com">
StackOverflow.com</a> community for help here and there.</p>