<p>UberGallery is a simple, yet powerful, PHP photo gallery that
will basically manage itself for you. UberGallery supports .jpg, .gif
and .png image types, and will automatically creates thumbnails on the
fly. The main feature of this gallery is it automatically outputs XHTML
compliant markup for inclusion on a web page. The UberGallery will also
automatically prune it's thumbnails, so when you delete an image from
the images folder, it will delete the corresponding thumbnail. The
gallery also creates a log file for reference and debugging. The
UberGallery is licensed under the MIT License.</p>

<p>UberGallery also includes dynamic pagination. This allows users
with larger galleries to split the gallery up into several smaller pages
so visitors can easily browse those pages using a navigation bar below
the gallery. GZip compression is also implemented on the default
index.php file included with the gallery which helps to reduce bandwidth
usage and improves page load times significantly.</p>

<p>Starting with v1.6.3 UberGallery is dual licensed under the <a href="http://creativecommons.org/licenses/MIT/">MIT license</a> and <a href="http://creativecommons.org/licenses/GPL/2.0/">GPL 2.0 license</a>.</p>

<div class="hr"><hr /></div>

<h2>Download</h2>

<ul class="dl-box">
    <li>
        <a href="http://github.com/PHLAK/ubergallery/downloads" title="Download UberGallery">
            <strong>Download UberGallery</strong>
            <span class="version">v1.6.2</span><br />
            <span class="updated">Last Updated: February 2, 2010</span>
        </a>
    </li>
</ul>

<p class="changelog"><a href="http://ubergallery.tumblr.com/">View the Changelog</a></p>

<div class="hr"><hr /></div>

<h2>Contact</h2>

<p>If you have any questions or comments, please email the developer at:
<a href="mailto:Chris@ChrisKankiewicz.com">Chris@ChrisKankiewicz.com</a></p>

<div class="hr"><hr /></div>

<h2>Shout Outs</h2>
<p>Thanks go out to <a href="http://dualisanoob.com">Dual</a> for
inadvertently inspiring me to get up off my ass and program this.</p>

<p>Also, thanks to <a href="http://www.blastwavelabs.com">
Penguin</a> for answering questions throughout the entire development
process and for some bug testing.</p>

<p>Thanks also to <a href="http://www.wetwarehacks.com">Nak</a> for
rigorous beta testing that helped me iron out a number of bugs and fix
backwards capabilities.</p>

<p>Obligatory thanks to <a href="http://www.hexates.com">Hexatex</a>
for pen testing the crap out of this script and helping me find and
patch many vulnerabilities.</p>

<p>Lastly, thanks to the <a href="http://www.stackoverflow.com">
StackOverflow.com</a> community for help here and there.</p>