<h2>Simple Installation</h2>

<ol>
    <li>Upload index.php and the ubergallery directory to your web
    server where you would like the gallery to be displayed. (Example:
    http://www.domain-name.com/photo-gallery/)</li>
    <li>Upload your images to the ubergallery/images/ directory.</li>
    <li>Make the ubergallery/cache/ directory writable by the web
    server. <pre>chmod 777 -R /path/to/ubergallery/cache/</pre></li>
    <li>Open your web browser and navigate to the directory where you
    installed the gallery and the script should generate thumbnails and
    display your images.</li>
</ol>

<div class="hr"><hr /></div>

<h2>Install to Pre-Existing Web Page</h2>
<ol>
    <li>If you wish to change the name or location of the images
    folder, thumbnails folder or log file, or you would like to enable
    pagination, open index.php and edit the variables found at the top.</li>
    <li>Rename index.php to ubergallery.php</li>
    <li>Upload the newly created ubergallery.php and the entire
    ubergallery/ folder to your web server.</li>
    <li>Insert the following code into the page where you would like
    the gallery to be displayed: <pre>&lt;?php include('path/to/script/ubergallery.php'); ?&gt;</pre></li>
    <li>Copy the contentst of ubergallery/resources/css/gallery.css
    into your own style sheet or include it in your page and edit it to
    your liking.</li>
    <li>Upload your images to the images directory
    (ubergallery/images/ by default).</li>
    <li>Make the ubergallery/cache/ directory writable by the web server.
    <pre>chmod 777 -R /path/to/ubergallery/cache/</pre></li>
    <li>Navigate to the page in your browser and the script should
    generate thumbnails and display your images.</li>
</ol>